name: systemevents
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
      sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.0.0
  country_picker: ^2.0.0
  contactus: ^1.1.7
  http:
  smart_select:
  fluttertoast:
  geocoder: ^0.2.1
#audioplayers:
#flutter_audio_recorder2:
  path_provider: ^2.0.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider:
  shared_preferences: ^2.0.15
  icon_shadow: ^1.0.1
  android_intent:
  webview_flutter: ^3.0.0
  google_fonts: ^2.2.0
  connectivity:
  video_player: ^2.2.7
  firebase_core: ^1.18.0
  firebase_messaging: ^11.4.2
  platform_device_id: ^1.0.1
  great_circle_distance_calculator: ^1.0.3
#  geolocator: ^8.0.1
#  workmanager: ^0.2.0
#  flutter_local_notifications: ^9.2.0
  hovering: ^1.0.4
  flutter_secure_storage: ^5.0.2
  sqflite: ^2.0.2
  flutter_polyline_points: ^1.0.0
  telephony: ^0.2.0
  responsive_framework: ^0.1.7
  flutter_launcher_icons: ^0.9.2
  another_flushbar: ^1.10.28
  mockito: ^5.1.0
  font_awesome_flutter: ^10.1.0


  video_compress:
    git:
      url: https://github.com/jonataslaw/VideoCompress.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.12
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.png"
  adaptive_icon_background: "assets/images/ic_launcher_adaptive_back.png"
  adaptive_icon_foreground: "assets/images/ic_launcher_adaptive_fore.png"

dependency_overrides:
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0-nullsafety.2
  image_picker: ^0.8.5+3
  location: ^4.4.0
  google_maps_flutter: ^2.2.0
  flutter_google_places: ^0.3.0
  geocoding: ^2.0.5
  flutter_typeahead: ^4.1.0
  flutter_plugin_android_lifecycle: ^2.0.1
  plugin_platform_interface: ^2.0.0
  geolocator: ^9.0.1
  workmanager: ^0.5.0
  flutter_local_notifications: ^9.9.1

  get: ^4.6.5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #  fonts:
  #
  #   - family: Tahoma
  #     fonts:
  #       asset: assets/fonts/tahoma.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
